apiVersion: v1
kind: Pod
metadata:
   name: myapp1
spec:
   containers:
      - image: nginx:alpine
        name: cont1
        ports:
---
apiVersion: v1
kind: Pod
metadata:
   name: dosconte
spec:
   containers:
      - image: python:3.6-alpine
        name: cont2
        command: ['sh', '-c',  'echo "cont2" > index.html && pyhton -m http.server 8082']
      - image: python:3.6-alpine
        name: cont3
        command: ['sh', '-c',  'echo "cont2" > index.html && pyhton -m http.server 8082']
