apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-test
  labels:
    app: rs-test
    #tier: frontend
spec:
  # modifica las réplicas según tu caso de uso, cada que borres un pod se crea uno automatico
  replicas: 5
  selector:
    matchLabels:
      app: pod-label
  #Desde aqui comienza los pods    
  template:
    metadata:
      labels:
        app: pod-label
    spec:
      containers:
      - name:  container1
        image: nginx:alpine
      - name:  container2 
        image: nginx:alpine
         
